# spring
spring:
  application:
    # 应用名称
    name: cms
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/cms?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

# mybatis
mybatis:
  mapper-locations:
    - classpath:com/**/mapper/*DaoImpl.xml
    - classpath:mapper/*DaoImpl.xml

# slf4j
logging:
  level:
    root: info




